backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/gallery"
public_folder: "/media"
site_url: liskola.com
editor:
  preview: false

collections:
  - name: "pages"
    label: "Pages"
    description: "Edit pages"
    files:
      - name: "quote"
        label: "Edit quote"
        file: "content/_index.md"
        description: "Quote has three section: quote, quoter and the quoter's title. Quoter and quoter's title are all capitalized."
        fields:
          - { label: "Quoter", name: "quote", widget: "string" }
          - { label: "Quoter's Title", name: "quoteTitle", widget: "string" }
          - { label: "Quote", name: "body", widget: "markdown" }
